// Code generated by protoc-gen-go. DO NOT EDIT.
// source: address.proto

package address

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Address type
type Address struct {
	AddressLine_1        string   `protobuf:"bytes,1,opt,name=address_line_1,json=addressLine1,proto3" json:"address_line_1,omitempty"`
	AddressLine_2        string   `protobuf:"bytes,2,opt,name=address_line_2,json=addressLine2,proto3" json:"address_line_2,omitempty"`
	ZipCode              string   `protobuf:"bytes,3,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddressLine_1() string {
	if m != nil {
		return m.AddressLine_1
	}
	return ""
}

func (m *Address) GetAddressLine_2() string {
	if m != nil {
		return m.AddressLine_2
	}
	return ""
}

func (m *Address) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func init() {
	proto.RegisterType((*Address)(nil), "moneytree.svc.address.Address")
}

func init() { proto.RegisterFile("address.proto", fileDescriptor_982c640dad8fe78e) }

var fileDescriptor_982c640dad8fe78e = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x49, 0x29,
	0x4a, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xcd, 0xcd, 0xcf, 0x4b, 0xad,
	0x2c, 0x29, 0x4a, 0x4d, 0xd5, 0x2b, 0x2e, 0x4b, 0xd6, 0x83, 0x4a, 0x2a, 0xcd, 0x63, 0xe4, 0x62,
	0x77, 0x84, 0xb0, 0x85, 0x54, 0xb8, 0xf8, 0xa0, 0xc2, 0xf1, 0x39, 0x99, 0x79, 0xa9, 0xf1, 0x86,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x3c, 0x50, 0x51, 0x9f, 0xcc, 0xbc, 0x54, 0x43, 0x0c,
	0x55, 0x46, 0x12, 0x4c, 0x18, 0xaa, 0x8c, 0x84, 0x24, 0xb9, 0x38, 0xaa, 0x32, 0x0b, 0xe2, 0x93,
	0xf3, 0x53, 0x52, 0x25, 0x98, 0xc1, 0xf2, 0xec, 0x55, 0x99, 0x05, 0xce, 0xf9, 0x29, 0xa9, 0x42,
	0x42, 0x5c, 0x2c, 0xc9, 0x99, 0x25, 0x95, 0x12, 0x2c, 0x60, 0x61, 0x30, 0x5b, 0x48, 0x82, 0x8b,
	0x3d, 0x39, 0xbf, 0x34, 0xaf, 0xa4, 0xa8, 0x52, 0x82, 0x15, 0xa2, 0x1a, 0xca, 0x75, 0x32, 0x8f,
	0x32, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xce, 0x28, 0xca,
	0x2c, 0x2e, 0xcf, 0xcc, 0xc9, 0xc9, 0x4c, 0xcc, 0x2d, 0x36, 0xb4, 0x34, 0x37, 0xd7, 0x87, 0x7b,
	0x4b, 0x17, 0xec, 0xcf, 0x62, 0x7d, 0xa8, 0x33, 0x92, 0xd8, 0xc0, 0x7c, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x0f, 0x10, 0xec, 0x53, 0x08, 0x01, 0x00, 0x00,
}
