// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Balance              int32    `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Account) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Account) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Account) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type AccountRequest struct {
	AccountNumber        string   `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (m *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(m, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

type AccountResponse struct {
	Account              *Account   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Accounts             []*Account `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (m *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(m, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *AccountResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "moneytree.svc.account.Account")
	proto.RegisterType((*AccountRequest)(nil), "moneytree.svc.account.AccountRequest")
	proto.RegisterType((*AccountResponse)(nil), "moneytree.svc.account.AccountResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0xb5, 0xfb, 0x55, 0x9d, 0x65, 0x57, 0x18, 0x50, 0x82, 0x07, 0x29, 0x85, 0x95, 0x3d, 0xe5,
	0xb0, 0x1e, 0x14, 0x6f, 0xae, 0x07, 0x6f, 0x1e, 0xea, 0x49, 0x0f, 0x4a, 0x1a, 0x06, 0x11, 0xdc,
	0xa4, 0x26, 0xe9, 0x42, 0x7f, 0x81, 0xff, 0xc7, 0x5f, 0x28, 0xa6, 0x49, 0x45, 0x10, 0xaa, 0xe0,
	0xa9, 0x33, 0xd3, 0xf7, 0xe6, 0xcd, 0x7b, 0x04, 0x66, 0x42, 0x4a, 0x5d, 0x2b, 0xc7, 0x2b, 0xa3,
	0x9d, 0xc6, 0x83, 0x8d, 0x56, 0xd4, 0x38, 0x43, 0xc4, 0xed, 0x56, 0xf2, 0xf0, 0x33, 0x7f, 0x82,
	0xf4, 0xb2, 0x2d, 0xf1, 0x10, 0x26, 0xaa, 0xde, 0x94, 0x64, 0x58, 0x92, 0x25, 0xcb, 0xbd, 0x22,
	0x74, 0x88, 0x30, 0x72, 0x4d, 0x45, 0x6c, 0xe0, 0xa7, 0xbe, 0xfe, 0xc4, 0x5a, 0x27, 0x5c, 0x6d,
	0xd9, 0xb0, 0xc5, 0xb6, 0x1d, 0x32, 0x48, 0x4b, 0xf1, 0x22, 0x94, 0x24, 0x36, 0xca, 0x92, 0xe5,
	0xb8, 0x88, 0x6d, 0x7e, 0x06, 0xf3, 0x20, 0x54, 0xd0, 0x6b, 0x4d, 0xd6, 0xe1, 0x02, 0xe6, 0xe1,
	0x8a, 0xc7, 0x6f, 0xba, 0xf1, 0xf0, 0x1b, 0x3f, 0xcc, 0xdf, 0x12, 0xd8, 0xef, 0x98, 0xb6, 0xd2,
	0xca, 0x12, 0x9e, 0x43, 0x1a, 0x40, 0x9e, 0x33, 0x5d, 0x1d, 0xf3, 0x1f, 0xed, 0xf1, 0x48, 0x8c,
	0x70, 0xbc, 0x80, 0xdd, 0x50, 0x5a, 0x36, 0xc8, 0x86, 0xbf, 0xa0, 0x76, 0xf8, 0xd5, 0xfb, 0xa0,
	0xf3, 0x70, 0x4b, 0x66, 0xfb, 0x2c, 0x09, 0xef, 0x60, 0x76, 0x65, 0x48, 0x38, 0x8a, 0x21, 0xf6,
	0x6c, 0x3b, 0x3a, 0xe9, 0x51, 0x0b, 0x0e, 0xf3, 0x1d, 0x7c, 0x80, 0xe9, 0x35, 0xb9, 0x30, 0xb7,
	0xb8, 0xe8, 0x23, 0xfa, 0x50, 0xff, 0xb0, 0x9f, 0x00, 0xbf, 0xf6, 0xaf, 0x9b, 0x36, 0xed, 0x7f,
	0x97, 0x59, 0xa7, 0xf7, 0x63, 0xff, 0x00, 0xcb, 0x89, 0xff, 0x9c, 0x7e, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xcc, 0x21, 0xd5, 0x1f, 0x98, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AccountService service

type AccountServiceClient interface {
	CreateAccount(ctx context.Context, in *Account, opts ...client.CallOption) (*AccountResponse, error)
	GetAccounts(ctx context.Context, in *AccountRequest, opts ...client.CallOption) (*AccountResponse, error)
	GetAccountByNumber(ctx context.Context, in *AccountRequest, opts ...client.CallOption) (*AccountResponse, error)
}

type accountServiceClient struct {
	c           client.Client
	serviceName string
}

func NewAccountServiceClient(serviceName string, c client.Client) AccountServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "moneytree.svc.account"
	}
	return &accountServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *Account, opts ...client.CallOption) (*AccountResponse, error) {
	req := c.c.NewRequest(c.serviceName, "AccountService.CreateAccount", in)
	out := new(AccountResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccounts(ctx context.Context, in *AccountRequest, opts ...client.CallOption) (*AccountResponse, error) {
	req := c.c.NewRequest(c.serviceName, "AccountService.GetAccounts", in)
	out := new(AccountResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccountByNumber(ctx context.Context, in *AccountRequest, opts ...client.CallOption) (*AccountResponse, error) {
	req := c.c.NewRequest(c.serviceName, "AccountService.GetAccountByNumber", in)
	out := new(AccountResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccountService service

type AccountServiceHandler interface {
	CreateAccount(context.Context, *Account, *AccountResponse) error
	GetAccounts(context.Context, *AccountRequest, *AccountResponse) error
	GetAccountByNumber(context.Context, *AccountRequest, *AccountResponse) error
}

func RegisterAccountServiceHandler(s server.Server, hdlr AccountServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&AccountService{hdlr}, opts...))
}

type AccountService struct {
	AccountServiceHandler
}

func (h *AccountService) CreateAccount(ctx context.Context, in *Account, out *AccountResponse) error {
	return h.AccountServiceHandler.CreateAccount(ctx, in, out)
}

func (h *AccountService) GetAccounts(ctx context.Context, in *AccountRequest, out *AccountResponse) error {
	return h.AccountServiceHandler.GetAccounts(ctx, in, out)
}

func (h *AccountService) GetAccountByNumber(ctx context.Context, in *AccountRequest, out *AccountResponse) error {
	return h.AccountServiceHandler.GetAccountByNumber(ctx, in, out)
}
