// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number               string    `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Type                 string    `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Customer             *Customer `protobuf:"bytes,4,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Account) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Account) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type Response struct {
	Account              *Account   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Accounts             []*Account `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Response) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "moneytree.svc.account.Account")
	proto.RegisterType((*Response)(nil), "moneytree.svc.account.Response")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0xad, 0xd3, 0xaa, 0x4d, 0x2f, 0x6a, 0x86, 0x93, 0x40, 0x56, 0x07, 0x88, 0x32, 0x75, 0xf2,
	0x10, 0x16, 0x84, 0x58, 0xa0, 0x03, 0x33, 0x81, 0x89, 0xad, 0x75, 0x6f, 0xc8, 0x10, 0x3b, 0xb2,
	0x9d, 0x4a, 0xdd, 0x90, 0xf8, 0x2a, 0xfe, 0x0e, 0xc9, 0xb5, 0x23, 0x21, 0x81, 0x9a, 0xed, 0xfc,
	0xee, 0xdd, 0xbb, 0xf7, 0xce, 0xb0, 0xda, 0x49, 0xa9, 0x7b, 0xe5, 0x44, 0x67, 0xb4, 0xd3, 0x78,
	0xd5, 0x6a, 0x45, 0x27, 0x67, 0x88, 0x84, 0x3d, 0x4a, 0x11, 0x9a, 0xeb, 0x5c, 0xf6, 0xd6, 0xe9,
	0x96, 0xcc, 0x99, 0x56, 0x7e, 0x31, 0x58, 0x3c, 0x9d, 0x7b, 0x98, 0x43, 0xd2, 0x1c, 0x38, 0x2b,
	0xd8, 0x66, 0x59, 0x27, 0xcd, 0x01, 0xaf, 0x61, 0xae, 0xfa, 0x76, 0x4f, 0x86, 0x27, 0x1e, 0x0b,
	0x2f, 0x44, 0x98, 0xb9, 0x53, 0x47, 0x7c, 0xea, 0x51, 0x5f, 0xe3, 0x23, 0xa4, 0x51, 0x99, 0xcf,
	0x0a, 0xb6, 0xc9, 0xaa, 0x42, 0xfc, 0x76, 0x30, 0x2c, 0xde, 0x86, 0xa2, 0x1e, 0x26, 0xca, 0x4f,
	0x06, 0x69, 0x4d, 0xb6, 0xd3, 0xca, 0x12, 0xde, 0xc3, 0x22, 0xb8, 0xf5, 0x5e, 0xb2, 0xea, 0x46,
	0xfc, 0x99, 0x45, 0x04, 0xdf, 0x75, 0xa4, 0xe3, 0x03, 0xa4, 0xa1, 0xb4, 0x3c, 0x29, 0xa6, 0x23,
	0x46, 0x07, 0x7e, 0xf5, 0xcd, 0x20, 0x0f, 0xe8, 0x1b, 0x99, 0x63, 0x23, 0x09, 0xdf, 0x61, 0xb5,
	0x35, 0xb4, 0x73, 0x14, 0x0f, 0x74, 0x31, 0xd2, 0xfa, 0xf6, 0x9f, 0x7d, 0x31, 0x5c, 0x39, 0xc1,
	0x57, 0xc8, 0x5e, 0xc8, 0x05, 0x49, 0x3b, 0x42, 0xf3, 0x42, 0x86, 0x72, 0xf2, 0xbc, 0xfc, 0x88,
	0x27, 0xd8, 0xcf, 0xfd, 0xb7, 0xde, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x42, 0x76, 0x94,
	0x0e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AccountService service

type AccountServiceClient interface {
	CreateAccount(ctx context.Context, in *Customer, opts ...client.CallOption) (*Response, error)
	GetAccounts(ctx context.Context, in *Customer, opts ...client.CallOption) (*Account, error)
}

type accountServiceClient struct {
	c           client.Client
	serviceName string
}

func NewAccountServiceClient(serviceName string, c client.Client) AccountServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "moneytree.svc.account"
	}
	return &accountServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *Customer, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AccountService.CreateAccount", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccounts(ctx context.Context, in *Customer, opts ...client.CallOption) (*Account, error) {
	req := c.c.NewRequest(c.serviceName, "AccountService.GetAccounts", in)
	out := new(Account)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccountService service

type AccountServiceHandler interface {
	CreateAccount(context.Context, *Customer, *Response) error
	GetAccounts(context.Context, *Customer, *Account) error
}

func RegisterAccountServiceHandler(s server.Server, hdlr AccountServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&AccountService{hdlr}, opts...))
}

type AccountService struct {
	AccountServiceHandler
}

func (h *AccountService) CreateAccount(ctx context.Context, in *Customer, out *Response) error {
	return h.AccountServiceHandler.CreateAccount(ctx, in, out)
}

func (h *AccountService) GetAccounts(ctx context.Context, in *Customer, out *Account) error {
	return h.AccountServiceHandler.GetAccounts(ctx, in, out)
}
